WIP FEATURE: Translation Cache
sitegeist/Sitegeist.LostInTranslation pull request #16
Opened 2022-11-22 08:43 UTC by gradinarufelix

TBD

This PR is based on another pull-request. As soon as it is merged, this PR will be rebased to master.

2023-06-09 10:32 UTC, mficzel reviewed
I like this as it will help to limit the amount of translations actually sent to deepl. Necessary for the helper but also good for other cases.

2023-07-06 08:37 UTC, mficzel commented
I think this should this be enabled by default.

2023-07-06 08:39 UTC, mficzel requested changes
Other than enabling the caches by default i consider this fine.
With the eel helper in place caching has to be opt out.

2023-07-17 09:51 UTC, gradinarufelix commented
I adapted the default configuration and the Readme

2023-08-21 10:04 UTC, mficzel approved these changes

2023-08-21 10:15 UTC, merged