WIP FEATURE: Eel Helper
sitegeist/Sitegeist.LostInTranslation pull request #17
Opened 2022-11-22 08:44 UTC by gradinarufelix

TBD

This PR is based on another pull-request. As soon as it is merged, this PR will be rebased to master.

2023-05-30 14:39 UTC, mficzel requested changes
Other than the single question this is fine. Should definitely be backed by a cache in future.

2023-05-30 14:39 UTC, mficzel commented on Classes/Eel/TranslationHelper.php
> +        return $this->translationService->translate([$text], $targetLanguage, $sourceLanguage)[0];
`$sourceLanguage)[0]` sieht komisch aus. Bist du sicher.

2023-05-30 21:05 UTC, gradinarufelix commented on Classes/Eel/TranslationHelper.php
> +        return $this->translationService->translate([$text], $targetLanguage, $sourceLanguage)[0];
Ja. Wir schicken ein String-Array mit exakt einem Element hin und bekommen auch wieder ein String-Array mit exakt einem Element zurück.

Alternativ das?

```php
[$translatedText] = $this->translationService->translate([$text], $targetLanguage, $sourceLanguage);
return $translatedText;
```

2023-06-02 18:36 UTC, mficzel commented on Classes/Eel/TranslationHelper.php
> +        return $this->translationService->translate([$text], $targetLanguage, $sourceLanguage)[0];
Ahhh ... macht Sinn und ist korrekt. Mein Hirn findet sowas hier einfacher zu verstehen. Dein Vorschlag wäre aber auch fein für mich.
```
$translations = $this->translationService->translate([$text], $targetLanguage, $sourceLanguage);
return $translations[0];
```

2023-06-09 10:27 UTC, mficzel approved these changes

2023-06-09 10:27 UTC, merged